<?php
/**
 * Post author template part.
 *
 * 🚫🚫🚫
 * DO NOT EDIT THIS FILE WHILE INSIDE THE PLUGIN! Changes You make will be lost when a new version
 * of the AMP plugin is released. You need to copy this file out of the plugin and put it into your
 * custom theme, for example. To learn about how to customize these Reader-mode AMP templates, please
 * see: https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/
 * 🚫🚫🚫
 *
 * @package AMP
 */

/**
 * Context.
 *
 * @var AMP_Post_Template $this
 */

?>
<div>
	<!-- PMX-Imagen-Mov -->
   <!--  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<div class="visible-xs visible-sm">
<ins class="adsbygoogle"
     style="display:inline-block;width:336px;height:280px"
     data-ad-client="ca-pub-7512798297333598"
     data-ad-slot="2434676599"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>-->

<amp-ad
  width="100vw"
  height="320"
  type="adsense"
  data-ad-client="ca-pub-7512798297333598"
  data-ad-slot="2434676599"
  data-auto-format="rspv"
  data-full-width
>
  <div overflow></div>
</amp-ad>
<amp-ad
  width="100vw"
  height="320"
  type="adsense"
  data-ad-client="ca-pub-7512798297333598"
  data-ad-slot="7653611709"
  data-auto-format="rspv"
  data-full-width
>
  <div overflow></div>
</amp-ad>

</div>


